site_url: https://SatelliteShorelines.github.io/CoastSeg/
site_name: CoastSeg
site_description: An interactive toolbox for downloading satellite imagery, applying image segmentation models, mapping shoreline positions and more. The mapping extension for CoastSat and Zoo.
site_author: Sharon Fitzpatrick

repo_url: https://github.com/SatelliteShorelines/CoastSeg
repo_name: CoastSeg
edit_uri: edit/main/docs/

theme:
  name: material
  icon:
    logo: material/surfing
    favicon: material/surfing

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

plugins:
  - search

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation:
      - Basic Installation Guide: basic-install-guide.md
      - Secure Installation Guide: secure-install-guide.md
      - Mac Installation Guide: mac-install-guide.md
      - Update Guide: update-guide.md
  - Getting Started: getting-started.md
  - Case Studies:
      - Case Study 1 An Easy Location in Santa Cruz: case_study_1.md
      - Case Study 2 A Difficult Location in Alaska: case_study_2.md
  - Contributing:
      - Contribution Guide: Contribution-Guide.md
      - How to Run Test Scripts: contributing-run-tests.md
      - How to Add a New Workflow: contribute-a-workflow.md
      - Getting Started to Contribute: Getting-Started_to_contribute.md
      - How to Contribute Transects: contribute-transects.md
      - How to Test the Zoo Workflow: test-zoo-workflow.md
      - How to edit the website: edit-website.md
      # - Technical Documentation: technical-documentation.md
  - Tutorials:
      - How to authenticate with Google Earth Engine: how-to-auth.md
      - How to Use the Map: map_guide.md
      - How to Edit the Reference Shorelines: edit_reference_shorelines.md
      - How to use the ROI: roi.md
      - How to Download Imagery: how-to-download.md
      - Download Settings Guide: download_settings.md
      - How to Upload Features: how-to-upload-features.md
      - What is in a Session : what-is-in-a-session.md
      - How to Use Sessions: sessions.md
      - How to Use Sessions from Another User: how-to-use-a-session-another-user.md
      - How to Use Extract Shoreline Area: how-to-extract-shoreline-area.md
      - How to Extract Shorelines: extract_shorelines.md
      - Extract Shorelines Settings Guide: extract_shoreline_settings.md
      - How to Download the Tide Model: How-to-Download-Tide-Model.md
      - How to Tidally Correct: How-to-Tidally-Correct.md
      - How to Create Reference Shorelines & Transects & ROIs: How-to-Create-Reference-Shorelines-&-Transects&ROIs.md
      - How to Filter Bad Imagery: How-to-Filter-Out-Bad-Imagery.md
  - API Reference:
      - How to use CoastSeg API: CoastSeg-API-Guide.md
  - Zoo: models.md
  - Scripts:
      - How to Use Scripts: How-to-Use-Scripts.md
      - How to Use Apply Tidal Correction Script: Apply-Tidal_Correction_Script.md
      - How to Flip Transects: How-to-Use-Flip-Transects.md
      - How to Predict Tides: how_to_predicts_tides_script.md
      # - CoastSeg: scripts-coastseg.md
      # - CoastSat: scripts-coastsat.md
      # - Zoo: model.md
  - Roadmap: roadmap.md
